---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install
  - npm install -g ember

script:
  - npm test

before_deploy:
  - ember build --environment=production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  name: Yana Agun Siswanto
  email: yana.developer@gmail.com
